//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.DbConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qauntity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
