//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.ECommerceGPPDOperations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECommerceGPPDOperations.GPPD_ServiceSoap")]
    public interface GPPD_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        int Addition(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AdditionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtractrion", ReplyAction="*")]
        int Subtractrion(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtractrion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractrionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        int Multiplication(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplicationAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        int Division(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivisionAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse GetAllUsers(ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse> GetAllUsersAsync(ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse GetAllProducts(ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse> GetAllProductsAsync(ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCategories", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse GetAllCategories(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse> GetAllCategoriesAsync(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllServicesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServices", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse GetAllServices(ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServices", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse> GetAllServicesAsync(ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest request);
        
        // CODEGEN: Generating message contract since element name productJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.InsertProductResponse InsertProduct(ECommerceSite.ECommerceGPPDOperations.InsertProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.InsertProductResponse> InsertProductAsync(ECommerceSite.ECommerceGPPDOperations.InsertProductRequest request);
        
        // CODEGEN: Generating message contract since element name productJson from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse UpdateProduct(ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse> UpdateProductAsync(ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse DeleteProduct(ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse> DeleteProductAsync(ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(string GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody {
        
        public GetAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(string GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategories", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequestBody Body;
        
        public GetAllCategoriesRequest() {
        }
        
        public GetAllCategoriesRequest(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCategoriesRequestBody {
        
        public GetAllCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponseBody Body;
        
        public GetAllCategoriesResponse() {
        }
        
        public GetAllCategoriesResponse(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllCategoriesResult;
        
        public GetAllCategoriesResponseBody() {
        }
        
        public GetAllCategoriesResponseBody(string GetAllCategoriesResult) {
            this.GetAllCategoriesResult = GetAllCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServices", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequestBody Body;
        
        public GetAllServicesRequest() {
        }
        
        public GetAllServicesRequest(ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllServicesRequestBody {
        
        public GetAllServicesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponseBody Body;
        
        public GetAllServicesResponse() {
        }
        
        public GetAllServicesResponse(ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllServicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllServicesResult;
        
        public GetAllServicesResponseBody() {
        }
        
        public GetAllServicesResponseBody(string GetAllServicesResult) {
            this.GetAllServicesResult = GetAllServicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProduct", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.InsertProductRequestBody Body;
        
        public InsertProductRequest() {
        }
        
        public InsertProductRequest(ECommerceSite.ECommerceGPPDOperations.InsertProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productJson;
        
        public InsertProductRequestBody() {
        }
        
        public InsertProductRequestBody(string productJson) {
            this.productJson = productJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.InsertProductResponseBody Body;
        
        public InsertProductResponse() {
        }
        
        public InsertProductResponse(ECommerceSite.ECommerceGPPDOperations.InsertProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertProductResult;
        
        public InsertProductResponseBody() {
        }
        
        public InsertProductResponseBody(string InsertProductResult) {
            this.InsertProductResult = InsertProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(ECommerceSite.ECommerceGPPDOperations.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productJson;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(string productJson) {
            this.productJson = productJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(ECommerceSite.ECommerceGPPDOperations.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductResult;
        
        public UpdateProductResponseBody() {
        }
        
        public UpdateProductResponseBody(string UpdateProductResult) {
            this.UpdateProductResult = UpdateProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProduct", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.DeleteProductRequestBody Body;
        
        public DeleteProductRequest() {
        }
        
        public DeleteProductRequest(ECommerceSite.ECommerceGPPDOperations.DeleteProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteProductRequestBody() {
        }
        
        public DeleteProductRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECommerceSite.ECommerceGPPDOperations.DeleteProductResponseBody Body;
        
        public DeleteProductResponse() {
        }
        
        public DeleteProductResponse(ECommerceSite.ECommerceGPPDOperations.DeleteProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductResult;
        
        public DeleteProductResponseBody() {
        }
        
        public DeleteProductResponseBody(string DeleteProductResult) {
            this.DeleteProductResult = DeleteProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPPD_ServiceSoapChannel : ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPPD_ServiceSoapClient : System.ServiceModel.ClientBase<ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap>, ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap {
        
        public GPPD_ServiceSoapClient() {
        }
        
        public GPPD_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPPD_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPPD_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPPD_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addition(int a, int b) {
            return base.Channel.Addition(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(int a, int b) {
            return base.Channel.AdditionAsync(a, b);
        }
        
        public int Subtractrion(int a, int b) {
            return base.Channel.Subtractrion(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubtractrionAsync(int a, int b) {
            return base.Channel.SubtractrionAsync(a, b);
        }
        
        public int Multiplication(int a, int b) {
            return base.Channel.Multiplication(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicationAsync(int a, int b) {
            return base.Channel.MultiplicationAsync(a, b);
        }
        
        public int Division(int a, int b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int a, int b) {
            return base.Channel.DivisionAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllUsers(ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public string GetAllUsers() {
            ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequestBody();
            ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllUsersAsync(ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllUsersResponse> GetAllUsersAsync() {
            ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllUsersRequestBody();
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllProducts(ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public string GetAllProducts() {
            ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequestBody();
            ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllProductsAsync(ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllProductsResponse> GetAllProductsAsync() {
            ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllProductsRequestBody();
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllCategories(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategories(request);
        }
        
        public string GetAllCategories() {
            ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequestBody();
            ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllCategories(inValue);
            return retVal.Body.GetAllCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllCategoriesAsync(ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesResponse> GetAllCategoriesAsync() {
            ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllCategoriesRequestBody();
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllServices(ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest request) {
            return base.Channel.GetAllServices(request);
        }
        
        public string GetAllServices() {
            ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequestBody();
            ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllServices(inValue);
            return retVal.Body.GetAllServicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.GetAllServicesAsync(ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest request) {
            return base.Channel.GetAllServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.GetAllServicesResponse> GetAllServicesAsync() {
            ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest inValue = new ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.GetAllServicesRequestBody();
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).GetAllServicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.InsertProductResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.InsertProduct(ECommerceSite.ECommerceGPPDOperations.InsertProductRequest request) {
            return base.Channel.InsertProduct(request);
        }
        
        public string InsertProduct(string productJson) {
            ECommerceSite.ECommerceGPPDOperations.InsertProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.InsertProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.InsertProductRequestBody();
            inValue.Body.productJson = productJson;
            ECommerceSite.ECommerceGPPDOperations.InsertProductResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).InsertProduct(inValue);
            return retVal.Body.InsertProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.InsertProductResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.InsertProductAsync(ECommerceSite.ECommerceGPPDOperations.InsertProductRequest request) {
            return base.Channel.InsertProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.InsertProductResponse> InsertProductAsync(string productJson) {
            ECommerceSite.ECommerceGPPDOperations.InsertProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.InsertProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.InsertProductRequestBody();
            inValue.Body.productJson = productJson;
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).InsertProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.UpdateProduct(ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public string UpdateProduct(string productJson) {
            ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.UpdateProductRequestBody();
            inValue.Body.productJson = productJson;
            ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).UpdateProduct(inValue);
            return retVal.Body.UpdateProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.UpdateProductAsync(ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.UpdateProductResponse> UpdateProductAsync(string productJson) {
            ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.UpdateProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.UpdateProductRequestBody();
            inValue.Body.productJson = productJson;
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).UpdateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.DeleteProduct(ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest request) {
            return base.Channel.DeleteProduct(request);
        }
        
        public string DeleteProduct(int id) {
            ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.DeleteProductRequestBody();
            inValue.Body.id = id;
            ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse retVal = ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).DeleteProduct(inValue);
            return retVal.Body.DeleteProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse> ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap.DeleteProductAsync(ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest request) {
            return base.Channel.DeleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECommerceSite.ECommerceGPPDOperations.DeleteProductResponse> DeleteProductAsync(int id) {
            ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest inValue = new ECommerceSite.ECommerceGPPDOperations.DeleteProductRequest();
            inValue.Body = new ECommerceSite.ECommerceGPPDOperations.DeleteProductRequestBody();
            inValue.Body.id = id;
            return ((ECommerceSite.ECommerceGPPDOperations.GPPD_ServiceSoap)(this)).DeleteProductAsync(inValue);
        }
    }
}
